languageCode = "en"
languageName = "English"
weight = 1
title = "Joseph Shay"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "The journey of a lifetime"
dateFormat = "2 January 2006"
author = { name = "Yousef Shaykholeslam", headline = "Hey! I'm Yousef. I spend most of my time on robotic projects, playing intruments and play Volleyball, or watch some TV. My dream is to start a robotics company that helps and inspires other. Feel free to reach out to me. ", bio = "Trying to make the world a better place", links = [ { email = "mailto:gamer.exe_shay@yahoo.com" }, { github = "https://github.com/joseph-shay" }, { linkedin = "https://www.linkedin.com/in/joseph-shay-270448345?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app" }, { instagram = "https://www.instagram.com/jjoseph_exe/" }, { youtube = "https://www.youtube.com/@Josephs.robotics" }, { x-twitter = "https://twitter.com/jjoseph_exe" } ] }