[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "Projects"
pageRef = "Projects"
identifier = "VlNSeKPTTx"
weight = 20

[[main]]
name = "Rants "
pageRef = "Rants"
identifier = "GcT4AUgV3G"
weight = 30

[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Series"
pageRef = "Series"
weight = 20


