colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "projects" ]


[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "back.jpg"
showRecent = true
showRecentItems = "16"
showMoreLink = true
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
showMoreLinkDest = "/projects"


[article]
showDate = true
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = false
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showSummary = true
sharingLinks = [ "linkedin","telegram", "twitter", "whatsapp", "pinterest", "reddit", "facebook", "email" ]
layoutBackgroundBlur = true

[list]
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]
